on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n xxxxxvi -g xxxxxvi91b9-rg --location "West US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n xxxxxvi --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n xxxxxvi --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n xxxxxvi --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: xxxxxvi.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/WebApplication22" -f  "WebApplication22/Dockerfile" -t xxxxxvi.azurecr.io/alamo:${{ github.sha }}
        docker push xxxxxvi.azurecr.io/alamo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_alamo_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep alamo3ae2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace alamo3ae2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: alamo3ae2
        container-registry-url: xxxxxvi.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: alamodockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: alamo3ae2
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          xxxxxvi.azurecr.io/alamo:${{ github.sha }}
        imagepullsecrets: |
          alamodockerauth